### ISSUE TITLE
Work with circular grids

### ISSUE THREAD

**Issue by bobbinlace** [jo-pol/DiBL#6]
I make bobbin lace, want to do a circular grids and apply on them any of base elements of lace. Please tell me how to do it.

**Comment by jo-pol** [comment]
Do you have questions about the [user guide](https://github.com/jo-pol/DiBL/wiki/Polar-Grids) or about designing the lace on such a grid?

**Comment by bobbinlace** [comment]
Hello.
I wanted to introduce the basic elements of the lace into the net with the help of the program.
But I think that it is better to draw these elements in pencil on the printed grid.

Thank you for answer

**Comment by jo-pol** [comment]
This issue was moved to jo-pol/dibl-tensioned#6

**Comment by parkerdino01** [comment]
It's not working:(

**Comment by jo-pol** [comment]
Could you be more specific? Screenshots, web address, the sequence of actions you took, what you expected and what happened in stead?
